services:
  vue-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/frontend
      - /frontend/node_modules
    environment:
      - NODE_ENV=development    
    command:  yarn run serve
    #command:  yarn run build